import type { MathLevelConfig } from '../types'

export const K2_LEVELS: MathLevelConfig[] = [
  {
    gradeId: 'K–2',
    levelNumber: 1,
    title: 'Story problems up to 10',
    description: 'Solve short stories about balloons, birds, cars, and more.',
    questions: [
      {
        id: 'k2-l1-q1',
        type: 'single',
        prompt:
          'Mia has 3 red balloons and 2 blue balloons. Her friend gives her 2 more red balloons. How many red balloons does Mia have now?',
        options: ['3', '4', '5', '7'],
        answerIndex: 2,
        kangarooStyle: true,
      },
      {
        id: 'k2-l1-q2',
        type: 'single',
        prompt:
          'There are 5 birds on a fence. 2 birds fly away and then 1 new bird lands. How many birds are on the fence now?',
        options: ['3', '4', '5', '6'],
        answerIndex: 1,
        kangarooStyle: true,
      },
      {
        id: 'k2-l1-q3',
        type: 'single',
        prompt: 'Leo has 4 toy cars. He gets 3 more for his birthday. How many toy cars does Leo have now?',
        options: ['5', '6', '7', '8'],
        answerIndex: 2,
      },
      {
        id: 'k2-l1-q4',
        type: 'single',
        prompt: 'On the table there are 2 apples and 5 bananas. How many pieces of fruit are on the table?',
        options: ['5', '6', '7', '8'],
        answerIndex: 2,
      },
      {
        id: 'k2-l1-q5',
        type: 'single',
        prompt: 'A box holds exactly 5 crayons. You have 9 crayons. How many crayons will NOT fit in the box?',
        options: ['1', '2', '3', '4'],
        answerIndex: 1,
        kangarooStyle: true,
      },
      {
        id: 'k2-l1-q6',
        type: 'single',
        prompt: 'Jake has 6 stickers. He gives 2 to his sister. How many stickers does Jake have left?',
        options: ['3', '4', '5', '6'],
        answerIndex: 1,
      },
      {
        id: 'k2-l1-q7',
        type: 'single',
        prompt: 'Four ducks are in the pond. Three more ducks swim over. How many ducks are in the pond now?',
        options: ['5', '6', '7', '8'],
        answerIndex: 2,
      },
      {
        id: 'k2-l1-q8',
        type: 'single',
        prompt: 'Emma has 8 beads. She uses 5 to make a bracelet. How many beads does she have left?',
        options: ['2', '3', '4', '5'],
        answerIndex: 1,
      },
      {
        id: 'k2-l1-q9',
        type: 'single',
        prompt: 'Which number is bigger: 7 or 4?',
        options: ['4', '7', 'They are the same', 'I don\'t know'],
        answerIndex: 1,
      },
      {
        id: 'k2-l1-q10',
        type: 'single',
        prompt: 'Sam has 3 green marbles and 4 blue marbles. How many marbles does Sam have in total?',
        options: ['5', '6', '7', '8'],
        answerIndex: 2,
      },
      {
        id: 'k2-l1-q11',
        type: 'single',
        prompt: 'Ten cookies are on a plate. The family eats 6. How many cookies are left?',
        options: ['3', '4', '5', '6'],
        answerIndex: 1,
      },
      {
        id: 'k2-l1-q12',
        type: 'single',
        prompt: 'A basket has 2 peaches and 6 plums. How many pieces of fruit are in the basket?',
        options: ['6', '7', '8', '9'],
        answerIndex: 2,
      },
      {
        id: 'k2-l1-q13',
        type: 'single',
        prompt: 'Which number is smaller: 5 or 9?',
        options: ['5', '9', 'They are the same', 'I don\'t know'],
        answerIndex: 0,
      },
      {
        id: 'k2-l1-q14',
        type: 'single',
        prompt: 'Lily picks 4 flowers in the morning and 5 in the afternoon. How many flowers did she pick in all?',
        options: ['7', '8', '9', '10'],
        answerIndex: 2,
      },
      {
        id: 'k2-l1-q15',
        type: 'single',
        prompt: 'Seven fish are in a tank. The teacher moves 2 to another tank. How many fish stay in the first tank?',
        options: ['4', '5', '6', '7'],
        answerIndex: 1,
      },
      {
        id: 'k2-l1-q16',
        type: 'single',
        prompt: 'Tom has 1 red ball and 8 blue balls. How many balls does Tom have?',
        options: ['7', '8', '9', '10'],
        answerIndex: 2,
      },
      {
        id: 'k2-l1-q17',
        type: 'single',
        prompt: 'A shelf has 9 books. Mom adds 1 more book. How many books are on the shelf now?',
        options: ['8', '9', '10', '11'],
        answerIndex: 2,
      },
      {
        id: 'k2-l1-q18',
        type: 'single',
        prompt: 'Six rabbits are in the garden. Three run into the woods. How many rabbits are still in the garden?',
        options: ['2', '3', '4', '5'],
        answerIndex: 1,
      },
      {
        id: 'k2-l1-q19',
        type: 'single',
        prompt: 'Zara has 5 toy dinosaurs. Her brother gives her 4 more. How many dinosaurs does Zara have now?',
        options: ['7', '8', '9', '10'],
        answerIndex: 2,
      },
      {
        id: 'k2-l1-q20',
        type: 'single',
        prompt: 'Ten seeds are on the ground. A bird eats 7 of them. How many seeds are left?',
        options: ['1', '2', '3', '4'],
        answerIndex: 2,
      },
    ],
  },
]
